/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData accessibility = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender_alt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData genderless_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adult = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_big = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circled2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData street_view = IconData(0xf21d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender = IconData(0xf224, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData genderless = IconData(0xf22d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_hanging = IconData(0xf5cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
